### ISSUE TITLE
Support Switch Expressions

### ISSUE THREAD

**Issue by gtach2o** [c2nes/javalang#72]
https://openjdk.java.net/jeps/361

If you don't have time, could you at least give some tips how to fix it properly?
Would be enough to change  only ```parse_switch_block_statement_group``` or  something else should be done?

**Comment by c2nes** [comment]
I suspect that at a minimum that top-level expression parsing would also need to be updated to account for the fact that a `switch` can now be used as an expression and not just a statement. 

Fair warning though, there have been a lot of syntax changes in Java since Java 7 which this library originally targeted. Java 8 is _mostly_ supported at this point, but it was largely bolted onto the existing support for Java 7. I suspect adding support for Java 9+ features will get increasingly difficult without significant refactoring of the parser being required.

Unfortunately, I'm no longer actively using or working on javalang myself, but I would be willing to review a PR that added switch expression support with test coverage for changed code paths.

**Comment by gtach2o** [comment]
Thank you for response! I need to think about it 🤔
